export const Status = {
    SUCCESS: 'SUCCESS',
    ERROR: 'ERROR',
    SERVER_ERROR: 'SERVER_ERROR',
    INVALID_EMAIL_OR_PASSWORD: 'INVALID_EMAIL_OR_PASSWORD',
    TOKEN_NOT_FOUND: 'TOKEN_NOT_FOUND',
    USERNAME_ALREADY_EXISTS: 'USERNAME_ALREADY_EXISTS',
    EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
    ERROR_GETTING_CATEGORIES: 'ERROR_GETTING_CATEGORIES',
    ERROR_GETTING_RECOMMENDED: 'ERROR_GETTING_RECOMMENDED',
} as const

export type StatusType = typeof Status[keyof typeof Status]